[package]
name = "file_combiner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.32", features = ["derive"] }
colored = "3.0.0"
dialoguer = "0.11.0"
regex = "1.11.1"
walkdir = "2.5.0"
